### ISSUE TITLE
OpenVSX

### ISSUE THREAD

**Issue by SlinkousArt** [paradise-theme/vscode#2]
Could you add it to [OpenVSX](https://open-vsx.org/) to allow for Code - OSS users to use the theme without patching?

**Comment by Manas140** [comment]
Well, I'm not sure about that cause It seems to work just fine for me even if it's on vscode marketplace. and yes I'm using Code - OSS

**Comment by SlinkousArt** [comment]
Weird, I'm using OSS on arch, and it's not showing up.
